//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using thewayshop.Controllers;

namespace thewayshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int MaSP { get; set; }
        public int MaLoaiSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> GiaHienHanh { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
        public Nullable<decimal> GiaThuc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayThemSP { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh01 { get; set; }
        public string HinhAnh02 { get; set; }
        public string HinhAnh03 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }

        public ShowcaseType LayLoaiTrungBay()
        {
            if (NgayThemSP > DateTime.Today.AddMonths(-2)) return ShowcaseType.New;
            else if (KhuyenMai > 0) return ShowcaseType.Sale;
            return ShowcaseType.Normal;
        }
    }
}

public enum ShowcaseType
{
    New,
    Sale,
    Normal
}